# -*- coding: utf-8 -*-
"""KNN_resolver_erro

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ITSd1es43_714FpZTGDo7olH78fr4B01
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

dados = pd.read_csv("Testes_ML_classi_filtro2.csv")

x = dados[["Sexo","trabalha","pos_estudos","saude","engravidou" ,"Solitude","Fumou","Pais_Fumante","amigod_drogados","idade"]]
y = dados[["Ja_bebeu"]]

from sklearn.model_selection import train_test_split

x_treino, x_teste, y_treino, y_teste = train_test_split(x,y,test_size=0.3,random_state=42)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=17, p=2)

knn.fit(x_treino, y_treino)

labels = knn.predict(x_teste)

from sklearn.metrics import accuracy_score

acuracia = accuracy_score(teste_y, previsoes) * 100